# Getting started with the Numpy

<h3>-> How to import Numpy?</h3>

In [2]:
import numpy as np  

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


<h3>-> Why use Numpy?</h3>

We use NumPy because it's much faster and more memory-efficient than Python lists when dealing with large amounts of same-type (homogeneous) data. It also provides powerful functions for numerical operations, making data processing easier and faster.

👉 Use Python lists for small, mixed-type data.

👉 Use NumPy arrays for large, numerical, same-type data.

<h3>-> Use of NumPy Arrays (ndarray)</h3>

✅ Short Explanation: Use of NumPy Arrays (ndarray)
NumPy arrays are used for efficient storage and computation of large sets of same-type (homogeneous) data in multiple dimensions (1D, 2D, 3D, etc.). They're ideal for numerical operations like matrix math, data processing, simulations, and more.

🚫 Restrictions of NumPy Arrays
Same Data Type
→ All elements must be of the same type (e.g., all integers or all floats).

Fixed Size
→ Once created, the total number of elements can’t change.

Rectangular Shape
→ All rows must have the same number of columns (no jagged or uneven rows).

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"The matrice is of {a.shape} order")
print(f"The matrice is: \n{a}")

The matrice is of (3, 3) order
The matrice is: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


-> arrays are mutable and slicing is possible in Numpy (py)

In [5]:
a = np.array([[1, 2, 3, 4, 5, 6], [10, 20, 30, 40, 50, 60]])
b = np.array([7, 8, 9, 10, 11, 12])

a[0][0] = 15
b[1] = 80 # mutability

print(f"a after slicing: {a[:1]}")
print(f"b after slicing: {b[:3]}") #slicing



a after slicing: [[15  2  3  4  5  6]]
b after slicing: [ 7 80  9]


<h3>Array Attributes</h3>

This section covers the ndim, shape, size, and dtype attributes of an array.

In [6]:
# The number of dimensions of an array is contained in the ndim attribute.
print(a)
print(f"It is a {a.ndim}D array")

[[15  2  3  4  5  6]
 [10 20 30 40 50 60]]
It is a 2D array


In [7]:
# The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print(a.shape)

(2, 6)


In [8]:
# The fixed, total number of elements in array is contained in the size attribute.
print(f"number of elements in a is {a.size}")
import math
a.size == math.prod(a.shape) # no. of rows * no. of columns

number of elements in a is 12


True

In [9]:
print(a.dtype) # # "int" for integer, "64" for 64-bit

int64


<h3>How to create a basic array</h3>

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

-> np.zeros() creates an array filled with 0's<br>
-> np.ones() creates an array filled with 1's<br>
-> np.empty() creates an array filled with random float values (increses speed!)

In [10]:
c = np.array([1,2,3])
d = np.zeros(3)
e = np.ones(3)
f = np.empty(3)
print(f"normal array: {c}")
print(f"array with zeros: {d}")
print(f"array with ones: {e}")
print(f"array with rand.vals: {f}")

normal array: [1 2 3]
array with zeros: [0. 0. 0.]
array with ones: [1. 1. 1.]
array with rand.vals: [0. 0. 0.]


In [11]:
c = np.arange(4)
print(c)
c = np.arange(2, 9, 2) # arrange(start, stop, step)
print(c)
c = np.linspace(0, 10, num=6)
# starts from 0 and ends with 10 divinding the array in 6 elements evenly
print(c)

[0 1 2 3]
[2 4 6 8]
[ 0.  2.  4.  6.  8. 10.]


-> Specifying your data type

In [12]:
x = np.ones(2, dtype=np.int64)
print(x)

[1 1]


<h3>Adding, removing, and sorting elements</h3>

This section covers np.sort(), np.concatenate()

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(f"sorted array: {np.sort(arr)}")
print(f"original array: {arr}") # sort the copy of the original array

sorted array: [1 2 3 4 5 6 7 8]
original array: [2 1 5 3 7 4 6 8]


-> argsort: returns indices that would sort an array (indirect sort)<br>
-> lexsort: performs a stable sort using multiple keys (e.g., sort by last name, then first)<br>
-> searchsorted: finds indices where elements should be inserted to maintain sorted order<br>
-> partition: partially sorts array so that k-th element is in its final sorted position


In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"The merged array: {np.concatenate((a, b))}")

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(np.concatenate((x, y), axis=0))

The merged array: [1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


<h3>How do you know the shape and size of an array?</h3>

In [15]:
# A 3D Array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]], 

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example)
print(array_example.size) # no. of elements
print(array_example.shape) # You have 3 boxes, each box contains 2 rows, and each row has 4 values.

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
24
(3, 2, 4)


<h3>Can you reshape an array?</h3>

In [16]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)
np.reshape(a, shape=(2, 3), order='C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

<h3>how to add a new axis to an array</h3>
You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)

# You can use np.expand_dims to add an axis at index position 1 with:
b = np.expand_dims(a, axis=1)
b.shape

(6,)
(1, 6)


(6, 1)

<h3>Indexing and slicing</h3>

In [18]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

five_up = (a >= 5)
print(a[five_up])

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print(c)

five_up = (a > 5) | (a == 5)
print(five_up)

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


<h3>How to create an array from existing data</h3>
This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [20]:
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

print(np.vstack((a1, a2))) # vertically stacked
print(np.hstack((a1, a2))) # horizontal stacked 

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [21]:
x = np.arange(1, 25).reshape(2, 12) # arrange 1 to 25 and reshape the matrix
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [22]:
# If you wanted to split this array into three equally shaped arrays, you would run:
print(np.hsplit(x, 3))

# If you wanted to split your array after the third and fourth column, you’d run:
print(np.hsplit(x, (3, 4)))

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


<h3>Basic array operations</h3>
This section covers addition, subtraction, multiplication, division, and more

In [23]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
print(f"data: {data}")
print(f"ones: {ones}")

print(f"The sum is: {data + ones}")
print(f"The diff is: {data - ones}")
print(f"The product is: {data * data}")
print(f"The division is: {data / data}")

data: [1 2]
ones: [1 1]
The sum is: [2 3]
The diff is: [0 1]
The product is: [1 4]
The division is: [1. 1.]


In [24]:
a = np.array([1, 2, 3, 4])
print(f"The sum is: {a.sum()}")

b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0)) # You can sum over the axis of rows with:
print(b.sum(axis=1)) # You can sum over the axis of columns with:

The sum is: 10
[3 3]
[2 4]


<h3>Broadcasting</h3>

In [25]:
data = np.array([1.0, 2.0])
print(data*1.6)

data = np.array([1,2,3])
print(f"max element: {data.max()}")
print(f"min element: {data.min()}")
print(f"sum is: {data.sum()}")

[1.6 3.2]
max element: 3
min element: 1
sum is: 6


for complex arrays....

In [26]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(f"The sum is: {a.sum()}")
print(f"The min num is: {a.min()}")
print(f"The min num of each col. is: {a.min(axis=0)}")

The sum is: 4.8595784
The min num is: 0.05093587
The min num of each col. is: [0.12697628 0.05093587 0.26590556 0.5510652 ]


<h3>Creating matrices</h3>

In [29]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

print(f"max element: {data.max()}")
print(f"min element: {data.min()}")
print(f"sum is: {data.sum()}")

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]
max element: 6
min element: 1
sum is: 21


In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0)) # only in the first column
print(data.max(axis=1)) # max of (1, 2), max of(5, 3), max of (4, 6)

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


Addition of two matrices...

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print(data + ones)

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]]) 
print(data + ones_row) # data + ((3x2) matrice full of 1's)

[[2 3]
 [4 5]]
[[2 3]
 [4 5]
 [6 7]]


In [ ]:
a = np.ones((4, 3, 2)) # 4 blocks, 3 rows, 2 columns
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


use of np.zeros(), np.ones(), np.random.random()

In [36]:
a = np.zeros((3, 2))
print(a)
a = np.ones((3, 2))
print(a)
a = np.random.random((3, 2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.65386756 0.69722524]
 [0.70535291 0.07947389]
 [0.2302601  0.61960638]]


<h3>How to get unique items and counts</h3>

This section covers np.unique(), return_index and return_counts

In [42]:
# Operations on 1-D array

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(f"The unique values: {unique_values}")

unique_values, indices_list = np.unique(a, return_index=True)
print(f"The indexes of those unique values: {indices_list}")

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(f"The count of occurances: {occurrence_count}")

The unique values: [11 12 13 14 15 16 17 18 19 20]
The indexes of those unique values: [ 0  2  3  4  5  6  7 12 13 14]
The count of occurances: [3 2 2 2 1 1 1 1 1 1]


In [51]:
# Operations on 2-D array

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(f"The unique values: {unique_values}")

unique_rows = np.unique(a_2d, axis=0)
print(unique_rows) # removed duplicate row

unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

print(indices)
print(occurrence_count)

The unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


<h3>Transposing and reshaping a matrix</h3>

This section covers arr.reshape(), arr.transpose(), arr.T

In [58]:
a = data.reshape(2, 3) # 2 rows and 3 columns 
print(a)

b = data.reshape(3, 2) # 3 rows and 2 columns 
print(b)

# Transpose of the matrices 
print(a.transpose()) # same column will become the same row
print(b.transpose())

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 3 5]
 [2 4 6]]


<h3>How to reverse an array</h3>

his section covers np.flip()

In [ ]:
# Operation on 1-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_array = np.flip(arr)
print(f"The reversed array: {reversed_array}")

# Operation on 2-D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d) # Whole matrix
print(reversed_arr)

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows) # same row

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

The reversed array: [8 7 6 5 4 3 2 1]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


<h3>Reshaping and flattening multidimensional arrays</h3>
This section covers .flatten(), ravel()<br>
There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.


In [70]:
# flatten creates a new copy of the original array
# changing values won't effect the original array
print("Example of flatten() ")
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x.flatten())

a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

# But in ravel() changing values will effect the original array
print("Example of ravel() ")
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

Example of flatten() 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
Example of ravel() 
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


<h3>How to access the docstring for more information</h3>

In [87]:
help(max)
a = np.array([1, 2, 3, 4, 5, 6])
a?
# gain more info by len?? instead of len?

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        d:\sarthak\vscode workshop\jupyter notebook(ps)\.venv\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-t

---

> 📌 Made with passion by **Sarthak Dharmik**  
> 🚀 Feel free to ⭐ the repo or suggest improvements!
